apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "django-app.fullname" . }}-config
  namespace: {{ .Values.global.namespace }}
data:
  DEBUG: {{ .Values.app.env.DEBUG | quote }}
  ALLOWED_HOSTS: {{ .Values.app.env.ALLOWED_HOSTS | quote }}
  DB_PORT: {{ .Values.app.env.DB_PORT | quote }}
